# Generated by Django 2.2 on 2020-03-13 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangosaml2idp_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users',
            new_name='User',
        ),
    ]
